# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       oxygen-fonts

# >> macros
# << macros

Summary:    A desktop/gui font family for integrated use with the KDE desktop
Version:    0.3.96
Release:    1
Group:      System/X11/Fonts
License:    OFL, GPL, GPL+FE
BuildArch:  noarch
URL:        https://projects.kde.org/projects/playground/artwork/oxygen-fonts
Source0:    http://download.kde.org/unstable/plasma/4.96.0/src/%{name}-%{version}.tar.xz
Source100:  oxygen-fonts.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  cmake
BuildRequires:  extra-cmake-modules
BuildRequires:  fontpackages-devel

%description
A desktop/gui font family for integrated use with the KDE desktop.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DLIB_INSTALL_DIR=%{_lib}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING-GPL+FE.txt COPYING-OFL
# >> files
# << files
